### ISSUE TITLE
Can't access https://cloudarchitecture.io/hacking. DNS error.

### ISSUE THREAD

**Issue by Iqrahaq** [undergroundwires/CEH-in-bullet-points#17]
Hello,

Just wanted to let you know that https://cloudarchitecture.io/hacking appears to be down.

**Comment by Iqrahaq** [comment]
It appears to be working again so closing this issue as resolved.

**Comment by undergroundwires** [comment]
Hi @Iqrahaq , thanks for the report. I registered this domain on AWS and it's down again now. I try to extend the time but cannot complete payment. This is escalated to AWS support and site will be back again once it's resolved (I can pay to them..).
