### ISSUE TITLE
Scanning Networks / Xmas Scan Diagram - Arrow for closed port is pointing the wrong direction

### ISSUE THREAD

**Issue by EnjoyTheJoke** [undergroundwires/CEH-in-bullet-points#6]
While performing a Xmas Scan if target port is closed, target will send a packet with RST flag up to the attacker. 
**Arrow should point from Target to Attacker.** 
Thanks for the bullet-points. Really helpful. Great content! :)

**Comment by EnjoyTheJoke** [comment]
Review filtered diagram for XMAS too, please.
Thanks

**Comment by undergroundwires** [comment]
Thank you for your clear report and contribution. I've fixed it now. 😊
